/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.awt.Dimension;
import java.awt.Toolkit;
import util.KoneksiDB;
import javax.swing.JOptionPane;

/**
 *
 * @author Dwi Prayoga
 */
public class Register_Form extends javax.swing.JFrame {

    /**
     * Creates new form Register_Form
     */
    private KoneksiDB koneksiDB;

    public Register_Form() {
        initComponents();
        koneksiDB = new KoneksiDB();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2 - this.getSize().width/2, dim.height/2 - this.getSize().height/2);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_password = new javax.swing.JPasswordField();
        tf_nohp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_nama = new javax.swing.JTextField();
        btn_daftar = new javax.swing.JButton();
        tf_usser = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lbl_kembali = new javax.swing.JLabel();

        jLabel6.setBackground(new java.awt.Color(8, 131, 149));
        jLabel6.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(8, 131, 149));
        jLabel6.setText("Nomer Hp");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(8, 131, 149));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logosioanjirbaru.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel8)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(8, 131, 149));
        jLabel1.setFont(new java.awt.Font("Poppins ExtraBold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(8, 131, 149));
        jLabel1.setText("Daftar Akun");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jLabel2.setBackground(new java.awt.Color(8, 131, 149));
        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(8, 131, 149));
        jLabel2.setText("Daftar Sebagai");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        tf_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usernameActionPerformed(evt);
            }
        });
        jPanel4.add(tf_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 200, -1));

        jLabel4.setBackground(new java.awt.Color(8, 131, 149));
        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(8, 131, 149));
        jLabel4.setText("Nama Lengkap");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        tf_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_passwordActionPerformed(evt);
            }
        });
        jPanel4.add(tf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 200, -1));

        tf_nohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nohpActionPerformed(evt);
            }
        });
        jPanel4.add(tf_nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 200, -1));

        jLabel5.setBackground(new java.awt.Color(8, 131, 149));
        jLabel5.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(8, 131, 149));
        jLabel5.setText("Username");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel7.setBackground(new java.awt.Color(8, 131, 149));
        jLabel7.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(8, 131, 149));
        jLabel7.setText("Nomer Hp");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        tf_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_namaActionPerformed(evt);
            }
        });
        jPanel4.add(tf_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 200, -1));

        btn_daftar.setText("Daftar");
        btn_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_daftarActionPerformed(evt);
            }
        });
        jPanel4.add(btn_daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        tf_usser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "umum", " " }));
        tf_usser.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                tf_usserAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tf_usser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usserActionPerformed(evt);
            }
        });
        jPanel4.add(tf_usser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 200, -1));

        jLabel3.setBackground(new java.awt.Color(8, 131, 149));
        jLabel3.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(8, 131, 149));
        jLabel3.setText("Password");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        lbl_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        lbl_kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_kembaliMouseClicked(evt);
            }
        });
        jPanel4.add(lbl_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 418, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 307, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usernameActionPerformed

    private void tf_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_passwordActionPerformed

    private void tf_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_namaActionPerformed

    private void tf_nohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nohpActionPerformed

    private void btn_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_daftarActionPerformed
        String nama = tf_nama.getText();
        String nohp = tf_nohp.getText();
        String username = tf_username.getText();
        String password = new String(tf_password.getPassword());
        String role = (String) tf_usser.getSelectedItem();

        // Validasi sederhana
        if (nama.isEmpty() || nohp.isEmpty() || username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon lengkapi semua kolom");
            return;
        }

        // Panggil method untuk menyimpan data pengguna ke dalam database
        koneksiDB.insertUser(nama, nohp, username, password, role);

        JOptionPane.showMessageDialog(this, "Registrasi berhasil sebagai " + role);

        // Reset form setelah registrasi berhasil
        tf_nama.setText("");
        tf_nohp.setText("");
        tf_username.setText("");
        tf_password.setText("");
        tf_usser.setSelectedIndex(0); // Kembali ke pilihan pertama di JComboBox
                            

        
    


    }//GEN-LAST:event_btn_daftarActionPerformed

    private void tf_usserAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tf_usserAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usserAncestorMoved

    private void tf_usserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usserActionPerformed

    private void lbl_kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_kembaliMouseClicked
        this.dispose();
        Login_Form login = new Login_Form();
       login.setVisible(true);
    }//GEN-LAST:event_lbl_kembaliMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
  
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Form().setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_daftar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_kembali;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JTextField tf_nohp;
    private javax.swing.JPasswordField tf_password;
    private javax.swing.JTextField tf_username;
    private javax.swing.JComboBox<String> tf_usser;
    // End of variables declaration//GEN-END:variables
}
